### ISSUE TITLE
Problem no attribute 'GenerativeModel'

### ISSUE THREAD

**Issue by hkhanal** [google-gemini/generative-ai-python#359]
### Description of the bug:

I recently got the error message 
`AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel'`

**Comment by singhniraj08** [comment]
@hkhanal, I am unable to replicate this error on our end. Can you please let us know which package version you are working with and try out with the latest release? 
I tried working with `0.5.4` release and the module upload works without any issues. Ref:
![image](https://github.com/google-gemini/generative-ai-python/assets/110809167/edc79111-98c6-4fac-b825-e8d7b7d61ea0)

**Comment by hkhanal** [comment]
@singhniraj08 I found reason for issue. my platform is running in python 3.8  which forced to download the lower version "generativeai". Thank you for replying .  I need to work a lot to upgrade python3. Is there a way to use this pakage to lower version of python ?

**Comment by singhniraj08** [comment]
@hkhanal, Latest Python SDK release supports Python 3.9 and above versions and bumping python version down may break latest SDK functionality. We would recommend you to upgrade the python version to avoid any issues. Thank you!
